version: '3'

networks:
    app-network:
        driver: bridge

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8.2
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network

    db:
        image: postgres:alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        volumes:
            - ./postgres:/var/lib/postgresql/data
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - app-network
